[package]
name = "benchmarks"
version = "0.1.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
milli = { path = "../milli" }

[dev-dependencies]
heed = "*" # we want to use the version milli uses
criterion = "0.3.4"

[build-dependencies]
anyhow = "1.0"
bytes = "1.0"
flate2 = "1.0.20"
convert_case = "0.4"
reqwest = { version = "0.11.3", features = ["blocking", "rustls-tls"], default-features = false }

[[bench]]
name = "songs"
harness = false

[[bench]]
name = "wiki"
harness = false
